[package]
name = "libsql-python"
version = "0.0.15"
edition = "2021"

[lib]
name = "libsql_experimental"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
libsql = { git = "https://github.com/tursodatabase/libsql/", rev = "2f1caebde007d30e98eb895b3d1a4a7001312bb5" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }
