[package]
name = "libsql-python"
version = "0.0.19"
edition = "2021"

[lib]
name = "libsql_experimental"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
libsql = { git = "https://github.com/tursodatabase/libsql/", rev = "4de573727ccd65225b9d4944d49cb61b89196e87" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }
