[package]
name = "libsql-python"
version = "0.0.18"
edition = "2021"

[lib]
name = "libsql_experimental"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
libsql = { git = "https://github.com/tursodatabase/libsql/", rev = "c032b9fc18a8dbac7b6e25cf9a7fd34af7dbb2e6" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }
