[package]
name = "libsql-python"
version = "0.0.16"
edition = "2021"

[lib]
name = "libsql_experimental"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
libsql = { git = "https://github.com/psarna/libsql/", rev = "a1d4c524ce81850a0991a1e99743c641ee7692f4" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }
